spring:
  datasource:
#    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/CSSConge}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/prestation_dev}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:lpdn}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  mail:
    host:
      smtp.gmail.com
    port: 587
    username: netrathior@gmail.com
    password: ckltchxqjifbvoif
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
        verify:
          host: http://localhost:8080
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      SalarierNinUnique: SALARIER_NIN_UNIQUE
springdoc:
  pathsToMatch: /api/**


# spring.devtools.remote.restart.enabled=false  


file:
  upload:
    dir: src/main/resources/static/dossier/
    dmt: src/main/resources/static/dmt/
